### ISSUE TITLE
중복 파일 삭제 및 정리

### ISSUE THREAD

**Issue by Lee-do-yeong** [Lee-do-yeong/R.S#18]
4명이나 되는 인원이 파일을 업로드하다보니 
중복되는 내용이나 파일이 있어서
추후 회의때 정리 필요합니다~

**Comment by Kim-Gang-Min** [comment]
알겠읍니다~

**Comment by Kim-Gang-Min** [comment]
아직 master랑 master-new branch가 merge가 안돼서 마스터에는 불필요 파일이 존재합니다.
merge 후에 정리하는 것을 추천합니다.

**Comment by Lee-do-yeong** [comment]
네^^
