### ISSUE TITLE
2020-06-25 업데이트  내용

### ISSUE THREAD

**Issue by Kim-Gang-Min** [Lee-do-yeong/R.S#35]
각종 논리적 모순 해결
특히 배팅 부분 배팅 금액에 대한 모순 해결

테스트 함수 구축
카드 받을 때 출력
배팅 금액 및 전체 배팅 금액 출력

**Comment by Lee-do-yeong** [comment]
전에 올리신 내용은 close 해주세요.

**Comment by Kim-Gang-Min** [comment]
예~
